// This file is automatically generated. Do not edit it directly.
export async function authenticateCronRequest(request: Request): Promise<Response | null> {
  // Allow Vercel native scheduled cron jobs
  if (request.headers.get("x-vercel-cron") === "1") {
    return null;
  }

  const currentSecret = process.env["LOVABLE_CRON_SECRET"] || process.env["CRON_SECRET"];
  const previousSecret = process.env["LOVABLE_CRON_SECRET_PREVIOUS"];

  if (!currentSecret) {
    return null;
  }

  const match = /^Bearer ([^\s,]+)$/.exec(request.headers.get("authorization") ?? "");
  const token = match?.[1];
  if (!token) {
    return new Response("Unauthorized: Missing Bearer token", { status: 401 });
  }

  const { createHash, timingSafeEqual } = await import("node:crypto");
  const digest = (value: string) => createHash("sha256").update(value, "utf8").digest();
  const providedDigest = digest(token);
  const currentMatches = timingSafeEqual(providedDigest, digest(currentSecret));
  const previousMatches = timingSafeEqual(providedDigest, digest(previousSecret ?? currentSecret));

  if (!currentMatches && !previousMatches) {
    return new Response("Unauthorized", { status: 401 });
  }

  return null;
}
